# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "OptiBoost Optimizer | Start Optimizing in Seconds"
masthead_title: " "
description: "Open Source Free Strategy Parameter Optimizer tool for TradingView as extension."

domain: byteboost.ai     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://byteboostbeta.webflow.io/ # the base hostname and protocol for your site, e.g. http://example.com

markdown: kramdown
kramdown:
  input: GFM


# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

include:
  - _pages

logo: "/assets/images/optiboost_logo.png"

atom_feed:
  hide: true

layout: single

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-4EW3247CHD"
    anonymize_ip: false 

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false


footer:
  links:
    - label: "Download"
      icon: "fa-solid fa-circle-down"
      url: "https://chrome.google.com/webstore/category/extensions"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Mau124/OptiBoost"
    - label: "Contact"
      icon: ""
      url: "/#contact-"
    - label: "Disclaimer"
      icon: ""
      url: /#disclaimer
    - label: "Privacy"
      icon: ""
      url: /privacy
    

plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jemoji
  - jekyll-include-cache

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

relative_links:
  enabled:     true
  collections: false


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
